### ISSUE TITLE
Reclaiming disk space

### ISSUE THREAD

**Issue by dtoubelis** [beeker1121/goque#10]
Would it be possible to make goque to reclaim disk space? The algorithm could be that if queue is empty and size of database file is larger than the initial extent (or a configurable limit) then delete it and re-create.

The motivation for this feature is that we want to use this queue for persisting some telemetry data when network connection goes down. The amount of data is quite substantial but these event do not occur often and application must stay online 24/7/365. So, the problem is that one outage can use a lot of disk space that is never returned back. Once system operates normally the queue will be very shallow.

The application may use few dozen queues at the same time but outages do not occur at the same time so waste of storage will multiply and can easily take system down if left unattended.

I suppose we could work around this problem by recreating the queues from outside but it would be nicer to have this feature in goque. Would it be possible to add this feature?

**Comment by TrevorEdris** [comment]
I would also like this feature for very similar reasons.

**Comment by ovaltzer** [comment]
I was under the impression that leveldb automatically compacts the data, isn't it?

**Comment by dtoubelis** [comment]
The trigger rule we use right now is if size on disk is larger than one database extent and queue is empty.

**Comment by beeker1121** [comment]
I would recommend doing this outside of the goque package.

This can be done by stopping any running instances of goque, and then writing a simple program in Go to open the same queue/stack directory to perform the `CompactRange` method on.
