### ISSUE TITLE
concurrent access to LevelDB in goque

### ISSUE THREAD

**Issue by sp98** [beeker1121/goque#14]
Hi,

I'm working on a restful microservice and using PrefixQueue. 

pq, err := goque.OpenPrefixQueue(DATADIR) 
gives error on concurrent access. That is, it fails on trying to access the db on concurrent API calls(or goroutines). 

error message- "resource temporarily unavailable"
PS - I'm closing the db after using it. 

Is there any workaround for this?  I need to be able to access the DB concurrently

**Comment by kamushadenes** [comment]
:+1

**Comment by jawr** [comment]
You can read and write from the queue concurrently. Use sync or another concurrent safe method of opening the queue and then use the pointer in multiple goroutines.

**Comment by beeker1121** [comment]
@jawr's answer is correct, sync the opening of the queue.
