### ISSUE TITLE
PriorityQueue's Length method returns wrong(?) number of elements

### ISSUE THREAD

**Issue by wngmnheiko** [beeker1121/goque#2]
When a PriorityQueue is already closed or dropped the Length method still returns the number of elements available before close/drop.

Maybe 0 or an error would be a better return value in this case.

**Comment by beeker1121** [comment]
Hmm, I'm open to hearing ideas on the best way to handle it, let's have that has the first option.

I'm thinking maybe there could be an error returned for each function if the stacks/queues are closed? Something like `ErrDBClosed`. This would return for all functions if the queue is enclosed, i.e. Enqueue, Dequeue, Peek, Update, etc. Right now, for those functions, it returns the default LevelDB errors.

If this new error is added, should it be returned for the Length function as well?

**Comment by beeker1121** [comment]
Nevermind on adding the error to the Length function, that should only return uint64.

**Comment by beeker1121** [comment]
Ok I think I'll merge the two ideas, should have a new commit here within an hour or so. Thank you!

**Comment by beeker1121** [comment]
Fixed this with commit 39d78f4aade884bbbf0c7de5977c6a597d03ed6e, thank you again!
