### ISSUE TITLE
Does not make a distinction between pointer-nil and value-zero

### ISSUE THREAD

**Issue by wngmnheiko** [beeker1121/goque#7]
if an object contains a pointer and is written to a queue (did only test it with priority queues) then reading the object from the queue can result in a different object when the dereferenced pointer has a zero value. In that case the pointer itself is nil instead of a pointer to a zero-value.

See the output of the following program:

package main

import (
    "fmt"
    "github.com/beeker1121/goque"
    "log"
)

type Obj struct {
    A *int
    B int
}

func (o Obj) String() string {
    if o.A != nil {
        return fmt.Sprintf("%v %v %v", o.A, *o.A, o.B)
    } else {
        return fmt.Sprintf("%v %v", o.A, o.B)
    }
}

func main() {
    queue, err := goque.OpenPriorityQueue("queuetest", goque.ASC)
    if err != nil {
        log.Fatal("OpenPriorityQueue()", err)
    }

```
o1 := Obj{new(int), 1}
*o1.A = 0 // not necessary
    // *o1.A = 10 // this will work
    // o1.A = nil // will work, too

log.Println("Writing to queue:", o1)

_, err = queue.EnqueueObject(0, o1)
if err != nil {
    log.Println("EnqueueObject()", o1, err)
}

item, err := queue.Dequeue()
if err != nil {
    log.Fatal("Dequeue()", err)
}
o2 := Obj{}
err = item.ToObject(&o2)
if err != nil {
    log.Fatal("ToObject()", err)
}

log.Println("Read from queue:", o2)

queue.Drop()
```

}

**Comment by beeker1121** [comment]
Just Googling on the gob package, I saw this post which looks like it might address this very thing: https://groups.google.com/forum/#!topic/golang-nuts/VnFs2Cv0_UY

Does this fix the issue?

**Comment by wngmnheiko** [comment]
Yes it looks like the gob package is the problem here. There are other problems with it, like fields that are structs that have only unexported fields. gob can't encode them either. I now use custom en-/decoder methods:
func (t *SomeType) MarshalBinary() ([]byte, error) {
	buf, err := json.Marshal(t)
	return buf, err
}
func (t *SomeType) UnmarshalBinary(data []byte) error {
	err := json.Unmarshal(data, t)
	return err
}

**Comment by beeker1121** [comment]
Nice fix, I might implement this as a feature update (JSON encoding of objects) if that's cool.

**Comment by beeker1121** [comment]
Added this in ef8bb7f
